/**
 * Mobile-only wording (Hinglish, friendly). Every key is editable by the super admin from the CMS
 * "Mobile text" collection (`mobile_text`) in the shared database; these are the bundled defaults.
 */
export const appText: { key: string; text: string }[] = [
  // onboarding / auth
  { key: "app.welcome.title", text: "Tax bharna ab easy hai 😎" },
  { key: "app.welcome.body", text: "ITR aur GST — bina CA ki bhasha ke. Simple sawaal, simple jawab, kaam done." },
  { key: "app.welcome.login", text: "Login karo" },
  { key: "app.welcome.register", text: "Naya account banao" },
  { key: "app.login.title", text: "Wapas swagat hai 👋" },
  { key: "app.login.email", text: "Email" },
  { key: "app.login.email.hint", text: "Jo email website pe use kiya tha, wahi yahan chalega." },
  { key: "app.login.password", text: "Password" },
  { key: "app.login.button", text: "Andar chalo" },
  { key: "app.login.noAccount", text: "Account nahi hai? Banao — 1 minute." },
  { key: "app.register.title", text: "Chalo shuru karein 🚀" },
  { key: "app.register.name", text: "Aapka naam" },
  { key: "app.register.name.hint", text: "Jaisa PAN card pe likha hai." },
  { key: "app.register.phone", text: "Mobile number" },
  { key: "app.register.phone.hint", text: "10 digit, bina +91." },
  { key: "app.register.pan", text: "PAN number (optional)" },
  { key: "app.register.pan.hint", text: "10 letters/numbers, e.g. ABCDE1234F. Baad mein bhi daal sakte ho." },
  { key: "app.register.password.hint", text: "Kam se kam 8 characters." },
  { key: "app.register.button", text: "Account banao" },
  { key: "app.register.haveAccount", text: "Pehle se account hai? Login karo." },

  // tabs
  { key: "app.tab.home", text: "Home" },
  { key: "app.tab.itr", text: "ITR" },
  { key: "app.tab.gst", text: "GST" },
  { key: "app.tab.money", text: "Paisa" },
  { key: "app.tab.me", text: "Me" },

  // home
  { key: "app.home.greeting", text: "Hey {name} 👋" },
  { key: "app.home.subtitle", text: "Aaj kya karna hai?" },
  { key: "app.home.itr.title", text: "Income Tax return bharo" },
  { key: "app.home.itr.body", text: "Salary ho ya dukaan — 5 simple steps mein." },
  { key: "app.home.gst.title", text: "GST return bharo" },
  { key: "app.home.gst.body", text: "Bills add karo, tax hum nikal denge." },
  { key: "app.home.money.title", text: "Mera paisa" },
  { key: "app.home.money.body", text: "Tax diya, refund aaya, investment — sab ek jagah." },
  { key: "app.home.cases.title", text: "Mere returns" },
  { key: "app.home.cases.empty", text: "Abhi koi return shuru nahi hua. Upar se shuru karo!" },
  { key: "app.home.notifications", text: "Updates" },
  { key: "app.home.help", text: "Samajh nahi aa raha? Expert se baat karo 💬" },

  // ITR wizard
  { key: "app.itr.start.title", text: "Aap kya karte ho?" },
  { key: "app.itr.start.body", text: "Isse hum sahi form (ITR-1 / ITR-4) khud chun lenge. Aapko form number yaad rakhne ki zaroorat nahi." },
  { key: "app.itr.type.salaried", text: "Naukri karta hoon (salary milti hai)" },
  { key: "app.itr.type.salaried.body", text: "Company se Form 16 milta hai." },
  { key: "app.itr.type.business", text: "Dukaan / business hai" },
  { key: "app.itr.type.business.body", text: "Kirana, trading, manufacturing, online selling…" },
  { key: "app.itr.type.professional", text: "Freelancer / professional hoon" },
  { key: "app.itr.type.professional.body", text: "Doctor, designer, tutor, consultant, driver-partner…" },
  { key: "app.itr.year", text: "Kis saal ka return?" },
  { key: "app.itr.year.hint", text: "Financial year = 1 April se 31 March. Abhi pichhle saal ka bharte hain." },
  { key: "app.itr.continue", text: "Aage badho" },
  { key: "app.itr.back", text: "Peeche" },
  { key: "app.itr.income.title", text: "Kitna kamaya? 💰" },
  { key: "app.itr.income.body", text: "Jo lagoo nahi hota, use 0 chhod do. Andaaz se bhi likh sakte ho, baad mein badal sakte ho." },
  { key: "app.itr.salary.total", text: "Saal ki total salary" },
  { key: "app.itr.salary.total.hint", text: "Form 16 Part B → 'Gross salary'. Ya 12 mahine ki salary jod lo." },
  { key: "app.itr.salary.tds", text: "Company ne jo tax kaata (TDS)" },
  { key: "app.itr.salary.tds.hint", text: "Form 16 Part A → 'Total tax deducted'." },
  { key: "app.itr.deductions.title", text: "Tax bachane wale kharche 🛡️" },
  { key: "app.itr.deductions.body", text: "LIC, PF, PPF, school fees, health insurance — ye sab tax kam karte hain. Jo nahi hai, 0 rakho." },
  { key: "app.itr.result.title", text: "Aapka tax result 🎉" },
  { key: "app.itr.result.body", text: "Humne dono tarike (purana aur naya regime) check kiye aur sasta wala chuna." },
  { key: "app.itr.result.oldRegime", text: "Purana tarika" },
  { key: "app.itr.result.newRegime", text: "Naya tarika" },
  { key: "app.itr.result.recommended", text: "Best for you" },
  { key: "app.itr.result.taxable", text: "Tax lagne wali income" },
  { key: "app.itr.result.tax", text: "Total tax" },
  { key: "app.itr.result.paid", text: "Pehle se diya" },
  { key: "app.itr.result.payable", text: "Aur dena hai" },
  { key: "app.itr.result.refund", text: "Refund milega 🥳" },
  { key: "app.itr.result.zero", text: "Kuch nahi dena, kuch nahi milega ✌️" },
  { key: "app.itr.submit", text: "Review ke liye bhejo" },
  { key: "app.itr.submitted.title", text: "Bhej diya! ✅" },
  { key: "app.itr.submitted.body", text: "Hamari team check karegi aur aapko update bhejegi. Status 'Mere returns' mein dekho." },
  { key: "app.itr.save", text: "Save karo" },
  { key: "app.itr.saved", text: "Saved ✔" },

  // GST
  { key: "app.gst.title", text: "GST — bills se return tak 🧾" },
  { key: "app.gst.body", text: "Pehle apni GST registration add karo, phir har mahine ke bills daalo. Tax hum nikal denge." },
  { key: "app.gst.profile.add", text: "GST registration add karo" },
  { key: "app.gst.profile.saved", text: "Registration save ho gayi ✔" },
  { key: "app.gst.newReturn", text: "Naya return shuru karo" },
  { key: "app.gst.month", text: "Kaunsa mahina?" },
  { key: "app.gst.month.hint", text: "Format: 2025-04 (saal-mahina)." },
  { key: "app.gst.returnType.hint", text: "GSTR-1 = aapne kya becha. GSTR-3B = tax ka hisaab aur payment. Zyada log dono bharte hain." },
  { key: "app.gst.invoices.title", text: "Bills 🧾" },
  { key: "app.gst.invoices.body", text: "Bechne ka bill = Sales. Kharidne ka bill = Purchase (isse tax kam hota hai)." },
  { key: "app.gst.invoice.sales", text: "Sales bill (maine becha)" },
  { key: "app.gst.invoice.purchase", text: "Purchase bill (maine kharida)" },
  { key: "app.gst.invoice.add", text: "Bill add karo" },
  { key: "app.gst.invoice.added", text: "Bill add ho gaya ✔" },
  { key: "app.gst.summary.title", text: "Tax ka hisaab 🧮" },
  { key: "app.gst.summary.output", text: "Sales pe tax (aapne liya)" },
  { key: "app.gst.summary.itc", text: "Purchase pe tax (credit milega)" },
  { key: "app.gst.summary.payable", text: "Sarkaar ko dena hai" },
  { key: "app.gst.summary.lateFee", text: "Late fee + interest" },
  { key: "app.gst.submit", text: "Review ke liye bhejo" },
  { key: "app.gst.empty", text: "Abhi koi bill nahi. Pehla bill add karo 👇" },

  // money
  { key: "app.money.title", text: "Mera paisa 💸" },
  { key: "app.money.body", text: "Tax kitna dena tha, kitna diya, refund kab aaya — sab yahan." },
  { key: "app.money.liability", text: "Total tax banta hai" },
  { key: "app.money.paid", text: "Diya hua" },
  { key: "app.money.outstanding", text: "Baaki" },
  { key: "app.money.refund", text: "Refund" },
  { key: "app.money.investments", text: "Investments" },
  { key: "app.money.payments", text: "Tax payments" },
  { key: "app.money.addPayment", text: "Tax payment add karo" },
  { key: "app.money.addInvestment", text: "Investment add karo" },
  { key: "app.money.empty", text: "Abhi kuch nahi. Add karke shuru karo." },

  // me
  { key: "app.me.title", text: "Meri profile" },
  { key: "app.me.pan", text: "PAN" },
  { key: "app.me.bank", text: "Bank account (refund isme aayega)" },
  { key: "app.me.ifsc", text: "IFSC code" },
  { key: "app.me.ifsc.hint", text: "Cheque book ya bank app mein milega, e.g. SBIN0001234." },
  { key: "app.me.save", text: "Save karo" },
  { key: "app.me.logout", text: "Logout" },
  { key: "app.me.language", text: "Bhasha: Hinglish (admin CMS se badal sakte hain)" },

  // status words
  { key: "app.status.DRAFT", text: "Draft — abhi aap bhar rahe ho" },
  { key: "app.status.SUBMITTED", text: "Bheja gaya — team dekh rahi hai" },
  { key: "app.status.UNDER_REVIEW", text: "Review ho raha hai 🔍" },
  { key: "app.status.QUERY_RAISED", text: "Team ne sawaal poocha hai ❗" },
  { key: "app.status.APPROVED", text: "Approved ✅" },
  { key: "app.status.FILED", text: "File ho gaya 🎉" },
  { key: "app.status.REJECTED", text: "Wapas aaya — dobara dekho" },
  { key: "app.status.COMPLETED", text: "Done ✅" },

  { key: "app.common.loading", text: "Ruko zara…" },
  { key: "app.common.retry", text: "Dobara try karo" },
  { key: "app.common.error", text: "Kuch gadbad ho gayi 😅" },
];
